### ISSUE TITLE
DualBase.eval does not literalize it's terms, which results in a missing step of simplification.

### ISSUE THREAD

**Issue by QQII** [bastikr/boolean.py#5]
For example:
```python
>>> parse("~A*~(~A+~B)")
AND(NOT(Symbol('A')), NOT(OR(NOT(Symbol('A')), NOT(Symbol('B')))))
```
By adding:
```python
term  = term.literalize()
```
after
```python
term = self.__class__(*args, eval=False)
```
to the method DualBase.eval, this fixes the problem:
```python
>>> parse("~A*~(~A+~B)")
FALSE
```

I have not reviewed the code for DualBase.eval to check that this will not cause any problems.

**Comment by QQII** [comment]
I've made a pull request with this change here: https://github.com/bastikr/boolean.py/pull/6

**Comment by bastikr** [comment]
Hi!
Thank you for your feedback and taking the time submitting a fix. I think sometimes literalizing might lead to uglier results, i.e. if there is one NOT before a longer nested expression it will then lead to many more NOTS but in most cases it probably gives a better result. Since still all tests pass I'm going to apply the changes. Explicitly stating the website for the documentation is definitely a good idea, so thank you again.
Cheers,
Sebastian

**Comment by QQII** [comment]
I didn't consider that actually, I guess a possible solution would be to try to simplify it then to un-literalize them.

**Comment by bastikr** [comment]
Let's just leave it at it is for now, if problems occur for anyone we might have to reconsider.
